Mesh quality output file: 1.qual
Reading 2D boundary geometry file 1.bdry
Reading patch #0
   Point #0 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E55F8
         Patch 008EA3DC
   Point #1 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5654
         Patch 008E55F8
   Point #2 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E56B0
         Patch 008E5654
   Point #3 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E570C
         Patch 008E56B0
   Point #4 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E570C
         Patch 008E5768
   Point #5 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E57C4
         Patch 008E5768
   Point #6 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5964
         Patch 008E57C4
   Point #7 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E59C0
         Patch 008E5964
   Point #8 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E59C0
         Patch 008E5A1C
   Point #9 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5A78
         Patch 008E5A1C
   Point #10 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5AD4
         Patch 008E5A78
   Point #11 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5E08
         Patch 008E5AD4
   Point #12 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5E64
         Patch 008E5E08
   Point #13 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5E64
         Patch 008E5EC0
   Point #14 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5F1C
         Patch 008E5EC0
   Point #15 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5F1C
         Patch 008E5F78
   Point #16 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E5FD4
         Patch 008E5F78
   Point #17 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6030
         Patch 008E5FD4
   Point #18 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E608C
         Patch 008E6030
   Point #19 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E608C
         Patch 008E60E8
   Point #20 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E60E8
         Patch 008E6144
   Point #21 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6144
         Patch 008E6748
   Point #22 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E67A4
         Patch 008E6748
   Point #23 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6800
         Patch 008E67A4
   Point #24 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6800
         Patch 008E685C
   Point #25 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E68B8
         Patch 008E685C
   Point #26 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6914
         Patch 008E68B8
   Point #27 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6970
         Patch 008E6914
   Point #28 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6970
         Patch 008E69CC
   Point #29 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6A28
         Patch 008E69CC
   Point #30 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6A84
         Patch 008E6A28
   Point #31 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6AE0
         Patch 008E6A84
   Point #32 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6AE0
         Patch 008E6B3C
   Point #33 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6B98
         Patch 008E6B3C
   Point #34 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6BF4
         Patch 008E6B98
   Point #35 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6C50
         Patch 008E6BF4
   Point #36 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6CAC
         Patch 008E6C50
   Point #37 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6CAC
         Patch 008E6D08
   Point #38 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6D64
         Patch 008E6D08
   Point #39 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6D64
         Patch 008E6DC0
   Point #40 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E6E1C
         Patch 008E6DC0
   Point #41 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E787C
         Patch 008E6E1C
   Point #42 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E78D8
         Patch 008E787C
   Point #43 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E78D8
         Patch 008E7934
   Point #44 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7934
         Patch 008E7990
   Point #45 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7990
         Patch 008E79EC
   Point #46 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7A48
         Patch 008E79EC
   Point #47 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7AA4
         Patch 008E7A48
   Point #48 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7AA4
         Patch 008E7B00
   Point #49 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7B5C
         Patch 008E7B00
   Point #50 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7B5C
         Patch 008E7BB8
   Point #51 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7C14
         Patch 008E7BB8
   Point #52 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7C14
         Patch 008E7C70
   Point #53 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7CCC
         Patch 008E7C70
   Point #54 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7D28
         Patch 008E7CCC
   Point #55 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7D84
         Patch 008E7D28
   Point #56 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7DE0
         Patch 008E7D84
   Point #57 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7E3C
         Patch 008E7DE0
   Point #58 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7E98
         Patch 008E7E3C
   Point #59 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7E98
         Patch 008E7EF4
   Point #60 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7EF4
         Patch 008E7F50
   Point #61 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7FAC
         Patch 008E7F50
   Point #62 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E7FAC
         Patch 008E8008
   Point #63 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E8064
         Patch 008E8008
   Point #64 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E8064
         Patch 008E80C0
   Point #65 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E80C0
         Patch 008E811C
   Point #66 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E811C
         Patch 008E8178
   Point #67 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E81D4
         Patch 008E8178
   Point #68 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E8230
         Patch 008E81D4
   Point #69 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E828C
         Patch 008E8230
   Point #70 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E82E8
         Patch 008E828C
   Point #71 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E82E8
         Patch 008E8344
   Point #72 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E83A0
         Patch 008E8344
   Point #73 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E83FC
         Patch 008E83A0
   Point #74 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E83FC
         Patch 008E8458
   Point #75 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E84B4
         Patch 008E8458
   Point #76 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E84B4
         Patch 008E8510
   Point #77 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E856C
         Patch 008E8510
   Point #78 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E856C
         Patch 008E85C8
   Point #79 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E8624
         Patch 008E85C8
   Point #80 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E8680
         Patch 008E8624
   Point #81 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9D64
         Patch 008E8680
   Point #82 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9D64
         Patch 008E9DC0
   Point #83 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9E1C
         Patch 008E9DC0
   Point #84 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9E78
         Patch 008E9E1C
   Point #85 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9ED4
         Patch 008E9E78
   Point #86 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9F30
         Patch 008E9ED4
   Point #87 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9F30
         Patch 008E9F8C
   Point #88 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9FE8
         Patch 008E9F8C
   Point #89 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008E9FE8
         Patch 008EA044
   Point #90 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA0A0
         Patch 008EA044
   Point #91 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA0FC
         Patch 008EA0A0
   Point #92 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA158
         Patch 008EA0FC
   Point #93 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA158
         Patch 008EA1B4
   Point #94 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA1B4
         Patch 008EA210
   Point #95 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA210
         Patch 008EA26C
   Point #96 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA2C8
         Patch 008EA26C
   Point #97 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA324
         Patch 008EA2C8
   Point #98 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA324
         Patch 008EA380
   Point #99 is a boundary point
      It does not have a small angle
      It has 2 patches connected to it
         Patch 008EA3DC
         Patch 008EA380
Copying the Bdry2D information
Finished copying the Bdry2D info
dXLo: -1.345825 dXHi: 1.345825 dYLo: -0.458701 dYHi: 0.458701
Going through patches to determine original discretization... Inserting vert (0.448608, 0.000000)
Inserting vert (0.445439, -0.028025)
Inserting vert (0.437123, -0.055222)
Inserting vert (0.422676, -0.080630)
Inserting vert (0.403108, -0.103501)
Inserting vert (0.378400, -0.122949)
Inserting vert (0.349007, -0.138182)
Inserting vert (0.315135, -0.148291)
Inserting vert (0.278125, -0.152900)
Inserting vert (0.238987, -0.151666)
Inserting vert (0.199366, -0.144848)
Inserting vert (0.163424, -0.135196)
Inserting vert (0.132366, -0.124300)
Inserting vert (0.107587, -0.114569)
Inserting vert (0.088996, -0.107577)
Inserting vert (0.073993, -0.101843)
Inserting vert (0.062138, -0.097914)
Inserting vert (0.052192, -0.094937)
Inserting vert (0.043529, -0.092504)
Inserting vert (0.035950, -0.090798)
Inserting vert (0.028999, -0.089249)
Inserting vert (0.022673, -0.088307)
Inserting vert (0.016726, -0.087683)
Inserting vert (0.010996, -0.087046)
Inserting vert (0.005461, -0.086803)
Inserting vert (-0.000000, -0.086594)
Inserting vert (-0.005461, -0.086803)
Inserting vert (-0.010996, -0.087046)
Inserting vert (-0.016726, -0.087683)
Inserting vert (-0.022673, -0.088307)
Inserting vert (-0.028999, -0.089249)
Inserting vert (-0.035950, -0.090798)
Inserting vert (-0.043529, -0.092504)
Inserting vert (-0.052192, -0.094937)
Inserting vert (-0.062138, -0.097914)
Inserting vert (-0.073993, -0.101843)
Inserting vert (-0.088996, -0.107577)
Inserting vert (-0.107587, -0.114569)
Inserting vert (-0.132366, -0.124300)
Inserting vert (-0.163424, -0.135196)
Inserting vert (-0.199366, -0.144848)
Inserting vert (-0.238987, -0.151666)
Inserting vert (-0.278125, -0.152900)
Inserting vert (-0.315135, -0.148291)
Inserting vert (-0.349007, -0.138182)
Inserting vert (-0.378400, -0.122949)
Inserting vert (-0.403108, -0.103501)
Inserting vert (-0.422676, -0.080630)
Inserting vert (-0.437123, -0.055222)
Inserting vert (-0.445439, -0.028025)
Inserting vert (-0.448608, -0.000000)
Inserting vert (-0.445439, 0.028025)
Inserting vert (-0.437123, 0.055222)
Inserting vert (-0.422676, 0.080630)
Inserting vert (-0.403108, 0.103501)
Inserting vert (-0.378400, 0.122949)
Inserting vert (-0.349007, 0.138182)
Inserting vert (-0.315135, 0.148291)
Inserting vert (-0.278125, 0.152900)
Inserting vert (-0.238987, 0.151666)
Inserting vert (-0.199366, 0.144848)
Inserting vert (-0.163424, 0.135196)
Inserting vert (-0.132366, 0.124300)
Inserting vert (-0.107587, 0.114569)
Inserting vert (-0.088996, 0.107577)
Inserting vert (-0.073993, 0.101843)
Inserting vert (-0.062138, 0.097914)
Inserting vert (-0.052192, 0.094937)
Inserting vert (-0.043529, 0.092504)
Inserting vert (-0.035950, 0.090798)
Inserting vert (-0.028999, 0.089249)
Inserting vert (-0.022673, 0.088307)
Inserting vert (-0.016726, 0.087683)
Inserting vert (-0.010996, 0.087046)
Inserting vert (-0.005461, 0.086803)
Inserting vert (-0.000000, 0.086594)
Inserting vert (0.005461, 0.086803)
Inserting vert (0.010996, 0.087046)
Inserting vert (0.016726, 0.087683)
Inserting vert (0.022673, 0.088307)
Inserting vert (0.028999, 0.089249)
Inserting vert (0.035950, 0.090798)
Inserting vert (0.043529, 0.092504)
Inserting vert (0.052192, 0.094937)
Inserting vert (0.062138, 0.097914)
Inserting vert (0.073993, 0.101843)
Inserting vert (0.088996, 0.107577)
Inserting vert (0.107587, 0.114569)
Inserting vert (0.132366, 0.124300)
Inserting vert (0.163424, 0.135196)
Inserting vert (0.199366, 0.144848)
Inserting vert (0.238987, 0.151666)
Inserting vert (0.278125, 0.152900)
Inserting vert (0.315135, 0.148291)
Inserting vert (0.349007, 0.138182)
Inserting vert (0.378400, 0.122949)
Inserting vert (0.403108, 0.103501)
Inserting vert (0.422676, 0.080630)
Inserting vert (0.437123, 0.055222)
Inserting vert (0.445439, 0.028025)
   Pass 1:     0 swaps,     0 total
Face swapping complete.
done.
Now trying to recover all of the edges... List of edges to be recovered contains 100 items
  0) iV0: 4, iV1: 5, iPatch: 0
  1) iV0: 5, iV1: 6, iPatch: 1
  2) iV0: 6, iV1: 7, iPatch: 2
  3) iV0: 7, iV1: 8, iPatch: 3
  4) iV0: 8, iV1: 9, iPatch: 4
  5) iV0: 9, iV1: 10, iPatch: 5
  6) iV0: 10, iV1: 11, iPatch: 6
  7) iV0: 11, iV1: 12, iPatch: 7
  8) iV0: 12, iV1: 13, iPatch: 8
  9) iV0: 13, iV1: 14, iPatch: 9
  10) iV0: 14, iV1: 15, iPatch: 10
  11) iV0: 15, iV1: 16, iPatch: 11
  12) iV0: 16, iV1: 17, iPatch: 12
  13) iV0: 17, iV1: 18, iPatch: 13
  14) iV0: 18, iV1: 19, iPatch: 14
  15) iV0: 19, iV1: 20, iPatch: 15
  16) iV0: 20, iV1: 21, iPatch: 16
  17) iV0: 21, iV1: 22, iPatch: 17
  18) iV0: 22, iV1: 23, iPatch: 18
  19) iV0: 23, iV1: 24, iPatch: 19
  20) iV0: 24, iV1: 25, iPatch: 20
  21) iV0: 25, iV1: 26, iPatch: 21
  22) iV0: 26, iV1: 27, iPatch: 22
  23) iV0: 27, iV1: 28, iPatch: 23
  24) iV0: 28, iV1: 29, iPatch: 24
  25) iV0: 29, iV1: 30, iPatch: 25
  26) iV0: 30, iV1: 31, iPatch: 26
  27) iV0: 31, iV1: 32, iPatch: 27
  28) iV0: 32, iV1: 33, iPatch: 28
  29) iV0: 33, iV1: 34, iPatch: 29
  30) iV0: 34, iV1: 35, iPatch: 30
  31) iV0: 35, iV1: 36, iPatch: 31
  32) iV0: 36, iV1: 37, iPatch: 32
  33) iV0: 37, iV1: 38, iPatch: 33
  34) iV0: 38, iV1: 39, iPatch: 34
  35) iV0: 39, iV1: 40, iPatch: 35
  36) iV0: 40, iV1: 41, iPatch: 36
  37) iV0: 41, iV1: 42, iPatch: 37
  38) iV0: 42, iV1: 43, iPatch: 38
  39) iV0: 43, iV1: 44, iPatch: 39
  40) iV0: 44, iV1: 45, iPatch: 40
  41) iV0: 45, iV1: 46, iPatch: 41
  42) iV0: 46, iV1: 47, iPatch: 42
  43) iV0: 47, iV1: 48, iPatch: 43
  44) iV0: 48, iV1: 49, iPatch: 44
  45) iV0: 49, iV1: 50, iPatch: 45
  46) iV0: 50, iV1: 51, iPatch: 46
  47) iV0: 51, iV1: 52, iPatch: 47
  48) iV0: 52, iV1: 53, iPatch: 48
  49) iV0: 53, iV1: 54, iPatch: 49
  50) iV0: 54, iV1: 55, iPatch: 50
  51) iV0: 55, iV1: 56, iPatch: 51
  52) iV0: 56, iV1: 57, iPatch: 52
  53) iV0: 57, iV1: 58, iPatch: 53
  54) iV0: 58, iV1: 59, iPatch: 54
  55) iV0: 59, iV1: 60, iPatch: 55
  56) iV0: 60, iV1: 61, iPatch: 56
  57) iV0: 61, iV1: 62, iPatch: 57
  58) iV0: 62, iV1: 63, iPatch: 58
  59) iV0: 63, iV1: 64, iPatch: 59
  60) iV0: 64, iV1: 65, iPatch: 60
  61) iV0: 65, iV1: 66, iPatch: 61
  62) iV0: 66, iV1: 67, iPatch: 62
  63) iV0: 67, iV1: 68, iPatch: 63
  64) iV0: 68, iV1: 69, iPatch: 64
  65) iV0: 69, iV1: 70, iPatch: 65
  66) iV0: 70, iV1: 71, iPatch: 66
  67) iV0: 71, iV1: 72, iPatch: 67
  68) iV0: 72, iV1: 73, iPatch: 68
  69) iV0: 73, iV1: 74, iPatch: 69
  70) iV0: 74, iV1: 75, iPatch: 70
  71) iV0: 75, iV1: 76, iPatch: 71
  72) iV0: 76, iV1: 77, iPatch: 72
  73) iV0: 77, iV1: 78, iPatch: 73
  74) iV0: 78, iV1: 79, iPatch: 74
  75) iV0: 79, iV1: 80, iPatch: 75
  76) iV0: 80, iV1: 81, iPatch: 76
  77) iV0: 81, iV1: 82, iPatch: 77
  78) iV0: 82, iV1: 83, iPatch: 78
  79) iV0: 83, iV1: 84, iPatch: 79
  80) iV0: 84, iV1: 85, iPatch: 80
  81) iV0: 85, iV1: 86, iPatch: 81
  82) iV0: 86, iV1: 87, iPatch: 82
  83) iV0: 87, iV1: 88, iPatch: 83
  84) iV0: 88, iV1: 89, iPatch: 84
  85) iV0: 89, iV1: 90, iPatch: 85
  86) iV0: 90, iV1: 91, iPatch: 86
  87) iV0: 91, iV1: 92, iPatch: 87
  88) iV0: 92, iV1: 93, iPatch: 88
  89) iV0: 93, iV1: 94, iPatch: 89
  90) iV0: 94, iV1: 95, iPatch: 90
  91) iV0: 95, iV1: 96, iPatch: 91
  92) iV0: 96, iV1: 97, iPatch: 92
  93) iV0: 97, iV1: 98, iPatch: 93
  94) iV0: 98, iV1: 99, iPatch: 94
  95) iV0: 99, iV1: 100, iPatch: 95
  96) iV0: 100, iV1: 101, iPatch: 96
  97) iV0: 101, iV1: 102, iPatch: 97
  98) iV0: 102, iV1: 103, iPatch: 98
  99) iV0: 103, iV1: 4, iPatch: 99
done.
Now deleting unnecessary cells and faces... done.
 Swapping to make sure everything is Delaunay...
   Pass 1:     0 swaps,     0 total
Face swapping complete.
Finished swapping, and it swapped 0 cells.
Setting up initial geometric length scale for mesh...
Updating length scale to take grading into account...
Done with grading check.
Done with length scale initialization.
Number of verts in initial triangulation:  100
Number of triangles in initial triangulation:  98
Evaluating quality of volume mesh...done.
Looking for small angles in the geometry
Done looking for small angles
Checking for large angles..
Done checking for large angles
Setting up initial geometric length scale for mesh...
Updating length scale to take grading into account...
Done with grading check.
Done with length scale initialization.
Starting Ruppert's with 98 cells, 197 faces and 100 verts
Inserted 249 vertices on this pass.
Inserted 0 vertices on this pass.
Ruppert's algorithm finished with 596 cells, 944 faces and 349 verts
Evaluating quality of volume mesh...done.
Number of triangles after refinement:  596
Smoothing vertices...
Pass 1 of 1...
Pass 1:    161 vertices moved by smoothing,    161 total
Vertex smoothing complete.
Evaluating quality of volume mesh...done.
Writing mesh to file(s)...
Done
Checked relative length scale for 1888 edges.
Average: 0.808128.  Min: 0.186577.  Max: 2.031706.
